LootJS.modifiers((event) => {
    const crops = [
        "minecraft:wheat",
        "minecraft:carrots",
        "minecraft:potatoes",
        "minecraft:beetroots",
        "minecraft:pumpkin",
        "minecraft:melon",
        "minecraft:cocoa",
        "minecraft:nether_wart",
        "minecraft:sugar_cane",
        "minecraft:cactus",
        "minecraft:bamboo",
        "minecraft:sweet_berry_bush",
        "minecraft:kelp",
        "minecraft:sea_pickle",
        "minecraft:chorus_flower",
        // Overworld
        "minecraft:stone",
        "minecraft:granite",
        "minecraft:polished_granite",
        "minecraft:diorite",
        "minecraft:polished_diorite",
        "minecraft:andesite",
        "minecraft:polished_andesite",
        "minecraft:grass_block",
        "minecraft:dirt",
        "minecraft:coarse_dirt",
        "minecraft:podzol",
        "minecraft:cobblestone",
        "minecraft:oak_planks",
        "minecraft:spruce_planks",
        "minecraft:birch_planks",
        "minecraft:jungle_planks",
        "minecraft:acacia_planks",
        "minecraft:dark_oak_planks",
        "minecraft:oak_sapling",
        "minecraft:spruce_sapling",
        "minecraft:birch_sapling",
        "minecraft:jungle_sapling",
        "minecraft:acacia_sapling",
        "minecraft:dark_oak_sapling",
        "minecraft:bedrock",
        "minecraft:sand",
        "minecraft:red_sand",
        "minecraft:gravel",
        "minecraft:gold_ore",
        "minecraft:iron_ore",
        "minecraft:coal_ore",
        "minecraft:nether_gold_ore",
        /*"minecraft:oak_log",
        "minecraft:spruce_log",
        "minecraft:birch_log",
        "minecraft:jungle_log",
        "minecraft:acacia_log",
        "minecraft:dark_oak_log",
        "minecraft:stripped_oak_log",
        "minecraft:stripped_spruce_log",
        "minecraft:stripped_birch_log",
        "minecraft:stripped_jungle_log",
        "minecraft:stripped_acacia_log",
        "minecraft:stripped_dark_oak_log",
        "minecraft:stripped_oak_wood",
        "minecraft:stripped_spruce_wood",
        "minecraft:stripped_birch_wood",
        "minecraft:stripped_jungle_wood",
        "minecraft:stripped_acacia_wood",
        "minecraft:stripped_dark_oak_wood",
        "minecraft:oak_wood",
        "minecraft:spruce_wood",
        "minecraft:birch_wood",
        "minecraft:jungle_wood",
        "minecraft:acacia_wood",
        "minecraft:dark_oak_wood",*/
        "#minecraft:logs",
        "#twilightforest:logs",
        "minecraft:sponge",
        "minecraft:wet_sponge",
        "minecraft:glass",
        "minecraft:lapis_ore",
        "minecraft:lapis_block",
        "minecraft:dispenser",
        "minecraft:sandstone",
        "minecraft:chiseled_sandstone",
        "minecraft:cut_sandstone",
        "minecraft:note_block",
        "minecraft:powered_rail",
        "minecraft:detector_rail",
        "minecraft:sticky_piston",
        "minecraft:cobweb",
        "minecraft:grass",
        "minecraft:fern",
        "minecraft:dead_bush",
        "minecraft:seagrass",
        "minecraft:sea_pickle",
        "minecraft:piston",
        "minecraft:white_wool",
        "minecraft:orange_wool",
        "minecraft:magenta_wool",
        "minecraft:light_blue_wool",
        "minecraft:yellow_wool",
        "minecraft:lime_wool",
        "minecraft:pink_wool",
        "minecraft:gray_wool",
        "minecraft:light_gray_wool",
        "minecraft:cyan_wool",
        "minecraft:purple_wool",
        "minecraft:blue_wool",
        "minecraft:brown_wool",
        "minecraft:green_wool",
        "minecraft:red_wool",
        "minecraft:black_wool",
        "minecraft:dandelion",
        "minecraft:poppy",
        "minecraft:blue_orchid",
        "minecraft:allium",
        "minecraft:azure_bluet",
        "minecraft:red_tulip",
        "minecraft:orange_tulip",
        "minecraft:white_tulip",
        "minecraft:pink_tulip",
        "minecraft:oxeye_daisy",
        "minecraft:cornflower",
        "minecraft:lily_of_the_valley",
        "minecraft:wither_rose",
        "minecraft:oak_slab",
        "minecraft:spruce_slab",
        "minecraft:birch_slab",
        "minecraft:jungle_slab",
        "minecraft:acacia_slab",
        "minecraft:dark_oak_slab",
        "minecraft:stone_slab",
        "minecraft:smooth_stone_slab",
        "minecraft:sandstone_slab",
        "minecraft:cut_sandstone_slab",
        "minecraft:petrified_oak_slab",
        "minecraft:cobblestone_slab",
        "minecraft:brick_slab",
        "minecraft:stone_brick_slab",
        "minecraft:nether_brick_slab",
        "minecraft:quartz_slab",
        "minecraft:red_sandstone_slab",
        "minecraft:cut_red_sandstone_slab",
        "minecraft:purpur_slab",
        "minecraft:prismarine_slab",
        "minecraft:prismarine_brick_slab",
        "minecraft:dark_prismarine_slab",
        "minecraft:smooth_quartz",
        "minecraft:smooth_red_sandstone",
        "minecraft:smooth_sandstone",
        "minecraft:smooth_stone",
        "minecraft:bricks",
        "minecraft:tnt",
        "minecraft:bookshelf",
        "minecraft:mossy_cobblestone",
        "minecraft:obsidian",
        "minecraft:torch",
        "minecraft:end_rod",
        "minecraft:chorus_plant",
        "minecraft:chorus_flower",
        "minecraft:purpur_block",
        "minecraft:purpur_pillar",
        "minecraft:purpur_stairs",
        "minecraft:purpur_slab",
        "minecraft:end_stone",
        "minecraft:end_stone_bricks",
        "minecraft:dragon_egg",
        "minecraft:redstone_lamp",
        "minecraft:sandstone_stairs",
        "minecraft:emerald_ore",
        "minecraft:ender_chest",
        "minecraft:tripwire_hook",
        "minecraft:emerald_block",
        "minecraft:spruce_stairs",
        "minecraft:birch_stairs",
        "minecraft:jungle_stairs",
        "minecraft:acacia_stairs",
        "minecraft:dark_oak_stairs",
        "minecraft:slime_block",
        "minecraft:barrier",
        "minecraft:iron_trapdoor",
        "minecraft:prismarine",
        "minecraft:prismarine_bricks",
        "minecraft:dark_prismarine",
        "minecraft:prismarine_stairs",
        "minecraft:prismarine_brick_stairs",
        "minecraft:dark_prismarine_stairs",
        "minecraft:hay_block",
        "minecraft:white_carpet",
        "minecraft:orange_carpet",
        "minecraft:magenta_carpet",
        "minecraft:light_blue_carpet",
        "minecraft:yellow_carpet",
        "minecraft:lime_carpet",
        "minecraft:pink_carpet",
        "minecraft:gray_carpet",
        "minecraft:light_gray_carpet",
        "minecraft:cyan_carpet",
        "minecraft:purple_carpet",
        "minecraft:blue_carpet",
        "minecraft:brown_carpet",
        "minecraft:green_carpet",
        "minecraft:red_carpet",
        "minecraft:black_carpet",
        "minecraft:terracotta",
        "minecraft:coal_block",
        "minecraft:packed_ice",
        "minecraft:sunflower",
        "minecraft:lilac",
        "minecraft:rose_bush",
        "minecraft:peony",
        "minecraft:tall_grass",
        "minecraft:large_fern",
        "minecraft:white_stained_glass",
        "minecraft:orange_stained_glass",
        "minecraft:magenta_stained_glass",
        "minecraft:light_blue_stained_glass",
        "minecraft:yellow_stained_glass",
        "minecraft:lime_stained_glass",
        "minecraft:pink_stained_glass",
        "minecraft:gray_stained_glass",
        "minecraft:light_gray_stained_glass",
        "minecraft:cyan_stained_glass",
        "minecraft:purple_stained_glass",
        "minecraft:blue_stained_glass",
        "minecraft:brown_stained_glass",
        "minecraft:green_stained_glass",
        "minecraft:red_stained_glass",
        "minecraft:black_stained_glass",
        "minecraft:white_stained_glass_pane",
        "minecraft:orange_stained_glass_pane",
        "minecraft:magenta_stained_glass_pane",
        "minecraft:light_blue_stained_glass_pane",
        "minecraft:yellow_stained_glass_pane",
        "minecraft:lime_stained_glass_pane",
        "minecraft:pink_stained_glass_pane",
        "minecraft:gray_stained_glass_pane",
        "minecraft:light_gray_stained_glass_pane",
        "minecraft:cyan_stained_glass_pane",
        "minecraft:purple_stained_glass_pane",
        "minecraft:blue_stained_glass_pane",
        "minecraft:brown_stained_glass_pane",
        "minecraft:green_stained_glass_pane",
        "minecraft:red_stained_glass_pane",
        "minecraft:black_stained_glass_pane",
        /*"minecraft:acacia_leaves",
        "minecraft:birch_leaves",
        "minecraft:dark_oak_leaves",
        "minecraft:jungle_leaves",
        "minecraft:oak_leaves",
        "minecraft:spruce_leaves",
        "minecraft:acacia_log",
        "minecraft:birch_log",
        "minecraft:dark_oak_log",
        "minecraft:jungle_log",
        "minecraft:oak_log",
        "minecraft:spruce_log",
        "minecraft:stripped_acacia_log",
        "minecraft:stripped_birch_log",
        "minecraft:stripped_dark_oak_log",
        "minecraft:stripped_jungle_log",
        "minecraft:stripped_oak_log",
        "minecraft:stripped_spruce_log",
        "minecraft:stripped_acacia_wood",
        "minecraft:stripped_birch_wood",
        "minecraft:stripped_dark_oak_wood",
        "minecraft:stripped_jungle_wood",
        "minecraft:stripped_oak_wood",
        "minecraft:stripped_spruce_wood",*/
        "#minecraft:leaves",
        "minecraft:bamboo",
        "minecraft:bamboo_sapling",
        "minecraft:barrel",
        "minecraft:blast_furnace",
        "minecraft:loom",
        "minecraft:lectern",
        "minecraft:smithing_table",
        "minecraft:composter",
        "minecraft:stonecutter",
        "minecraft:bells",
        "minecraft:sweet_berry_bush",
        "minecraft:lantern",
        "minecraft:campfire",
        "minecraft:bee_nest",
        "minecraft:beehive",
        "minecraft:honey_block",
        "minecraft:honeycomb_block",
    
        // Nether
        "minecraft:netherrack",
        "minecraft:soul_sand",
        "minecraft:soul_soil",
        "minecraft:basalt",
        "minecraft:polished_basalt",
        "minecraft:blackstone",
        "minecraft:polished_blackstone",
        "minecraft:polished_blackstone_bricks",
        "minecraft:cracked_polished_blackstone_bricks",
        "minecraft:chiseled_polished_blackstone",
        "minecraft:gilded_blackstone",
        "minecraft:nether_bricks",
        "minecraft:cracked_nether_bricks",
        "minecraft:chiseled_nether_bricks",
        "minecraft:red_nether_bricks",
        "minecraft:warped_nylium",
        "minecraft:crimson_nylium",
        "minecraft:nether_gold_ore",
        "minecraft:ancient_debris",
        "minecraft:crying_obsidian",
        "minecraft:glowstone",
        "minecraft:shroomlight",
        "minecraft:nether_wart_block",
        "minecraft:warped_wart_block",
        "minecraft:quartz_ore",
        "minecraft:nether_quartz_ore",
        "minecraft:magma_block",
        "minecraft:soul_torch",
        "minecraft:soul_lantern",
        "minecraft:soul_campfire",
        "minecraft:chain",
        "minecraft:warped_fungus",
        "minecraft:crimson_fungus",
        "minecraft:warped_roots",
        "minecraft:crimson_roots",
        "minecraft:nether_sprouts",
        "minecraft:weeping_vines",
        "minecraft:twisting_vines",
        "minecraft:crimson_stem",
        "minecraft:warped_stem",
        "minecraft:stripped_crimson_stem",
        "minecraft:stripped_warped_stem",
        "minecraft:crimson_planks",
        "minecraft:warped_planks",
        "minecraft:crimson_slab",
        "minecraft:warped_slab",
        "minecraft:crimson_pressure_plate",
        "minecraft:warped_pressure_plate",
        "minecraft:crimson_fence",
        "minecraft:warped_fence",
        "minecraft:crimson_trapdoor",
        "minecraft:warped_trapdoor",
        "minecraft:crimson_fence_gate",
        "minecraft:warped_fence_gate",
        "minecraft:crimson_stairs",
        "minecraft:warped_stairs",
        "minecraft:crimson_button",
        "minecraft:warped_button",
        "minecraft:crimson_door",
        "minecraft:warped_door",
        "minecraft:crimson_sign",
        "minecraft:warped_sign",
        "minecraft:nether_portal",
        "minecraft:respawn_anchor",
        "minecraft:lodestone",
        "minecraft:ancient_debris",
        "minecraft:crying_obsidian",
        "minecraft:blackstone",
        "minecraft:polished_blackstone",
        "minecraft:polished_blackstone_bricks",
        "minecraft:cracked_polished_blackstone_bricks",
        "minecraft:chiseled_polished_blackstone",
        "minecraft:gilded_blackstone",
        "minecraft:warped_stem",
        "minecraft:warped_hyphae",
        "minecraft:stripped_warped_stem",
        "minecraft:stripped_warped_hyphae",
        "minecraft:warped_nylium",
        "minecraft:warped_wart_block",
        "minecraft:warped_fence",
        "minecraft:warped_slab",
        "minecraft:warped_planks",
        "minecraft:warped_fence_gate",
        "minecraft:warped_stairs",
        "minecraft:warped_trapdoor",
        "minecraft:warped_door",
        "minecraft:warped_pressure_plate",
        "minecraft:warped_button",
        "minecraft:warped_sign",
        "minecraft:crimson_stem",
        "minecraft:crimson_hyphae",
        "minecraft:stripped_crimson_stem",
        "minecraft:stripped_crimson_hyphae",
        "minecraft:crimson_nylium",
        "minecraft:crimson_fence",
        "minecraft:crimson_slab",
        "minecraft:crimson_planks",
        "minecraft:crimson_fence_gate",
        "minecraft:crimson_stairs",
        "minecraft:crimson_trapdoor",
        "minecraft:crimson_door",
        "minecraft:crimson_pressure_plate",
        "minecraft:crimson_button",
        "minecraft:crimson_sign",
    
        // End
        "minecraft:end_stone",
        "minecraft:end_stone_bricks",
        "minecraft:dragon_egg",
        "minecraft:end_portal_frame",
        "minecraft:obsidian",
        "minecraft:end_stone_brick_slab",
        "minecraft:end_stone_brick_stairs",
        "minecraft:purpur_block",
        "minecraft:purpur_pillar",
        "minecraft:purpur_slab",
        "minecraft:purpur_stairs",
        "minecraft:chorus_flower",
        "minecraft:chorus_plant",
        "minecraft:shulker_box",
        "minecraft:white_shulker_box",
        "minecraft:orange_shulker_box",
        "minecraft:magenta_shulker_box",
        "minecraft:light_blue_shulker_box",
        "minecraft:yellow_shulker_box",
        "minecraft:lime_shulker_box",
        "minecraft:pink_shulker_box",
        "minecraft:gray_shulker_box",
        "minecraft:light_gray_shulker_box",
        "minecraft:cyan_shulker_box",
        "minecraft:purple_shulker_box",
        "minecraft:blue_shulker_box",
        "minecraft:brown_shulker_box",
        "minecraft:green_shulker_box",
        "minecraft:red_shulker_box",
        "minecraft:black_shulker_box",
        "minecraft:beacon",
        "minecraft:dragon_head",
        
        //TWILIGHT
        "twilight:twilight_oak_leaves"



    ];

    const lootModifiers = [
        //Raw
        { block: "minecraft:copper_ore", chance: 0.005, loot: "minecraft:raw_copper" },
        { block: "minecraft:iron_ore", chance: 0.005, loot: "minecraft:raw_iron" },
        { block: "minecraft:gold_ore", chance: 0.005, loot: "minecraft:raw_gold" },
        { block: "minecraft:diamond_ore", chance: 0.005, loot: "minecraft:diamond" },
        { block: "minecraft:lapis_ore", chance: 0.005, loot: "minecraft:lapis_lazuli" },
        { block: "minecraft:emerald_ore", chance: 0.005, loot: "minecraft:emerald" },
        { block: "minecraft:nether_quartz_ore", chance: 0.005, loot: "minecraft:quartz" },
        { block: "minecraft:nether_gold_ore", chance: 0.005, loot: "minecraft:gold_ingot" },
        { block: "minecraft:ancient_debris", chance: 0.005, loot: "minecraft:netherite_scrap" },
        //Essence
        { block: "minecraft:grass_block", chance: 0.007, loot: ["mysticalagriculture:nature_essence","mysticalagriculture:water_essence","mysticalagriculture:air_essence","mysticalagriculture:air_essence", "mysticalagriculture:fire_essence", "mysticalagriculture:earth_essence"] },
        { block: "#minecraft:leaves", chance: 0.005, loot: ["mysticalagriculture:nature_essence","mysticalagriculture:wood_essence","mysticalagriculture:air_essence"] },
        { block: "#minecraft:gravel", chance: 0.005, loot: "mysticalagriculture:fire_essence" },
        { block: "minecraft:stone", chance: 0.005, loot: ["mysticalagriculture:stone_essence" , "botania:pebble", "mysticalagriculture:fire_essence" ]},
        { block: "minecraft:cobblestone", chance: 0.005, loot: "mysticalagriculture:stone_essence" },
        { block: "#minecraft:logs", chance: 0.005, loot: "mysticalagriculture:wood_essence" },
        { block: "minecraft:ice", chance: 0.005, loot: ["mysticalagriculture:ice_essence", "mysticalagriculture:water_essence"] },
        { block: "minecraft:packed_ice", chance: 0.003, loot: ["mysticalagriculture:ice_essence", "mysticalagriculture:water_essence"] },
        { block: "minecraft:blue_ice", chance: 0.005, loot: ["mysticalagriculture:ice_essence", "mysticalagriculture:water_essence"] },
        { block: "minecraft:grass", chance: 0.015, loot: ["mysticalagriculture:water_essence", "mysticalagriculture:nature_essence"] },
        { block: "minecraft:tall_grass", chance: 0.025, loot: ["mysticalagriculture:water_essence", "mysticalagriculture:nature_essence"] },
        { block: "#minecraft:flowers", chance: 0.005, loot: "mysticalagriculture:dye_essence" },
        { block: "minecraft:obsidian", chance: 0.005, loot: "mysticalagriculture:obsidian_essence" },
        { block: "#minecraft:sand", chance: 0.005, loot: ["mysticalagriculture:air_essence", "mysticalagriculture:fire_essence"] },
        { block: "#minecraft:red_sand", chance: 0.005, loot: ["mysticalagriculture:air_essence", "mysticalagriculture:fire_essence"] },
        { block: "#minecraft:dirt", chance: 0.005, loot: ["mysticalagriculture:water_essence","mysticalagriculture:air_essence", "mysticalagriculture:fire_essence", "mysticalagriculture:earth_essence","mysticalagriculture:dirt_essence"] },
        { block: "#minecraft:sandstone", chance: 0.005, loot: "mysticalagriculture:fire_essence" },
        { block: "minecraft:deepslate", chance: 0.005, loot: "mysticalagriculture:deepslate_essence" },
        { block: "minecraft:cooble_deepslate", chance: 0.005, loot: "mysticalagriculture:deepslate_essence" },
        { block: "minecraft:nether_quartz_ore", chance: 0.005, loot: "mysticalagriculture:nether_quartz_essence" },
        { block: "minecraft:ancient_debris", chance: 0.005, loot: "mysticalagriculture:netherite_essence" },
        { block: "minecraft:netherrack", chance: 0.005, loot: "mysticalagriculture:nether_essence" },
        { block: "minecraft:nether_bricks", chance: 0.005, loot: "mysticalagriculture:nether_essence" },
        { block: "minecraft:soul_sand", chance: 0.005, loot: "mysticalagriculture:nether_essence" },
        { block: "minecraft:crimson_nylium", chance: 0.005, loot: "mysticalagriculture:nether_essence" },
        { block: "minecraft:warped_nylium", chance: 0.005, loot: "mysticalagriculture:nether_essence" },
        { block: "minecraft:coal_ore", chance: 0.005, loot: "mysticalagriculture:coal_essence" },
        { block: "minecraft:deepslate_coal_ore", chance: 0.005, loot: "mysticalagriculture:coal_essence" },
        { block: "energizedpowed:silicon_block", chance: 0.005, loot: "mysticalagriculture:silicon_essence" },
        { block: "#botania:mystical_flowers", chance: 0.005, loot: "mysticalagriculture:mystical_flower_essence" },
        { block: "#botania:double_mystical_flowers", chance: 0.010, loot: "mysticalagriculture:mystical_flower_essence" },
        { block: "minecraft:iron_ore", chance: 0.005, loot: "mysticalagriculture:iron_essence" },
        { block: "minecraft:deepslate_iron_ore", chance: 0.005, loot: "mysticalagriculture:iron_essence" },
        { block: "minecraft:deepslate_emerald_ore", chance: 0.005, loot: "mysticalagriculture:emerald_essence" },
        { block: "minecraft:deepslate_diamond_ore", chance: 0.005, loot: "mysticalagriculture:diamond_essence" },
        { block: "minecraft:end_stone", chance: 0.005, loot: "mysticalagriculture:end_essence" },
        { block: "minecraft:end_stone_bricks", chance: 0.005, loot: "mysticalagriculture:end_essence" },

        //TWILIGHT
        { block: "#minecraft:leaves", chance: 0.01, loot: "minecraft:apple" },
        { block: "#minecraft:leaves", chance: 0.005, loot: "minecraft:golden_apple" },
        { block: "#minecraft:leaves", chance: 0.0025, loot: "minecraft:enchanted_golden_apple" },
        { block: "#minecraft:leaves", chance: 0.00125, loot: "mysticalagradditions:inferium_apple" },
        { block: "#minecraft:leaves", chance: 0.000625, loot: "mysticalagradditions:prudentium_apple" },
        { block: "#minecraft:leaves", chance: 0.0003125, loot: "mysticalagradditions:tertium_apple" },
        { block: "#minecraft:leaves", chance: 0.0001562, loot: "mysticalagradditions:imperium_apple" },
        { block: "#minecraft:leaves", chance: 0.000078125, loot: "mysticalagradditions:supremium_apple" },
        { block: "#minecraft:leaves", chance: 0.0000390625, loot: "mysticalagradditions:insanium_apple" },

        //SPRUCE
        { block: "minecraft:spruce_leaves", chance: 0.02, loot: "minecraft:apple" },
        { block: "minecraft:spruce_leaves", chance: 0.01, loot: "minecraft:golden_apple" },
        { block: "minecraft:spruce_leaves", chance: 0.005, loot: "minecraft:enchanted_golden_apple" },
        { block: "minecraft:spruce_leaves", chance: 0.0025, loot: "mysticalagradditions:inferium_apple" },
        { block: "minecraft:spruce_leaves", chance: 0.00125, loot: "mysticalagradditions:prudentium_apple" },
        { block: "minecraft:spruce_leaves", chance: 0.000625, loot: "mysticalagradditions:tertium_apple" },
        { block: "minecraft:spruce_leaves", chance: 0.0003125, loot: "mysticalagradditions:imperium_apple" },
        { block: "minecraft:spruce_leaves", chance: 0.0001562, loot: "mysticalagradditions:supremium_apple" },
        { block: "minecraft:spruce_leaves", chance: 0.000078125, loot: "mysticalagradditions:insanium_apple" },










    ];

    const fertilizedEssence = "mysticalagriculture:fertilized_essence";
    const dropChance = 0.00085;

    crops.forEach(crop => {
        event.addBlockLootModifier(crop).randomChance(dropChance).addLoot(fertilizedEssence);
    });

    lootModifiers.forEach(modifier => {
        const blocks = Array.isArray(modifier.block) ? modifier.block : [modifier.block];
        const loots = Array.isArray(modifier.loot) ? modifier.loot : [modifier.loot];
        blocks.forEach(block => {
            loots.forEach(loot => {
                event.addBlockLootModifier(block).randomChance(modifier.chance).addLoot(loot);
            });
        });
    });
});
